# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'B_Category' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod "CTMediator"

end
